AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  Sample SAM Template for sam-app
   This template is partially managed by Amazon.Lambda.Annotations (v1.7.0.0).
Globals:
  Function:
    Timeout: 10
    MemorySize: 512
    LoggingConfig:
      LogFormat: JSON
Resources:
  HelloWorldFunctionFunctionHandlerGenerated:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
    Properties:
      Runtime: dotnet8
      CodeUri: src/HelloWorld
      MemorySize: 512
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      PackageType: Zip
      Handler: HelloWorld::HelloWorld.Function_FunctionHandler_Generated::FunctionHandler
Outputs:
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
